name = "oidcc"
version = "3.1.0"

description = "OpenID Connect client library for the BEAM."
licences = ["Apache-2.0"]
repository = { type = "github", user = "erlef", repo = "oidcc" }
links = [{ title = "Github", href = "https://github.com/erlef/oidcc" }]

target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.32"
jose = "~> 1.11"

[dev-dependencies]
gleeunit = "~> 1.0"
